export  const quotes = [
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine. - Roy T. Bennett",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Your limitation—it's only your imagination. - Unknown",
    "Push yourself, because no one else is going to do it for you. - Unknown",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Don't wait. The time will never be just right. - Napoleon Hill",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "You are the only one who can limit your greatness. - Unknown",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Your life does not get better by chance, it gets better by change. - Jim Rohn",
    "The best way to predict the future is to invent it. - Alan Kay",
    "You are never too old to set another goal or to dream a new dream. - Les Brown",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
    "The best revenge is massive success. - Frank Sinatra",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Don't limit your challenges, challenge your limits. - Unknown",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "You are never too old to set another goal or to dream a new dream. - Les Brown"
]